apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: kafka
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      - pattern: kafka.server<type=(.+), name=(.+)PerSec\w*><>Count
        name: kafka_server_$1_$2_total
        type: COUNTER
      - pattern: kafka.server<type=ReplicaManager, name=(UnderReplicatedPartitions|UnderMinIsrPartitionCount|OfflineReplicaCount)><>Value
        name: kafka_server_replicamanager_$1
        type: GAUGE
      - pattern: kafka.controller<type=KafkaController, name=(OfflinePartitionsCount|ActiveControllerCount)><>Value
        name: kafka_controller_$1
        type: GAUGE
